/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ramdom;

import java.util.Random;
import javax.swing.JOptionPane;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author namxg
 */
public class JFrameRandom extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form JFrameRandom
     */
    public JFrameRandom() {
        initComponents();
        setLocationRelativeTo(null);
        Thread t1 = new Thread(this);
        t1.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtVar = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        OK2 = new javax.swing.JButton();
        vt = new javax.swing.JButton();
        vina = new javax.swing.JButton();
        vn = new javax.swing.JToggleButton();
        lbltime = new javax.swing.JLabel();
        mobi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CODE BY BECO");

        jLabel2.setText("Số lượng: ");

        btnOK.setText("Tạo ngẫu nhiên");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setText("Thoát");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        OK2.setText("các đầu số dùng nhiều");
        OK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OK2ActionPerformed(evt);
            }
        });

        vt.setText("Viettel");
        vt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vtActionPerformed(evt);
            }
        });

        vina.setText("VinaPhone");
        vina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vinaActionPerformed(evt);
            }
        });

        vn.setText("Vietnamobile & Gmobile");
        vn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vnActionPerformed(evt);
            }
        });

        mobi.setText("MobilePhone");
        mobi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mobi, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vina, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(btnCancel))
                            .addComponent(OK2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vn)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbltime, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtVar, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbltime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(OK2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vina)
                    .addComponent(vt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mobi)
                    .addComponent(vn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mobiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobiActionPerformed
        if (valtdateFrom()) {

            Random rd = new Random();
            String sdt2;
            String[] d = {"089", "090", "093", "070", "079", "077", "076", "078"};

            try {
                int sl = Integer.parseInt(txtVar.getText());
                try {
                    try ( FileWriter fw = new FileWriter("SDTMobilePhone.txt")) {
                        for (int i = 0; i < sl; i++) {
                            int k = rd.nextInt(d.length);
                            int number = 1000000 + rd.nextInt(999999);
                            sdt2 = d[k] + number + ":123456";
                            fw.write(sdt2 + "\n");
                        }
                        fw.close();
                    }
                } catch (IOException ignored) {
                }
                JOptionPane.showMessageDialog(this, "Thành công");

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, e + "\nBạn Phải nhập ký tự số", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "bạn chưa nhập số lượng", "lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mobiActionPerformed

    private void vnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vnActionPerformed
        if (valtdateFrom()) {

            Random rd = new Random();
            String sdt2;
            String[] d = {"092", "056", "058", "099", "059"};

            try {
                int sl = Integer.parseInt(txtVar.getText());
                try {
                    try ( FileWriter fw = new FileWriter("SDTVietnamobile.Gmobile.txt")) {
                        for (int i = 0; i < sl; i++) {
                            int k = rd.nextInt(d.length);
                            int number = 1000000 + rd.nextInt(999999);
                            sdt2 = d[k] + number + ":123456";
                            fw.write(sdt2 + "\n");
                        }
                        fw.close();
                    }
                } catch (IOException ignored) {
                }
                JOptionPane.showMessageDialog(this, "Thành công");

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, e + "\nBạn Phải nhập ký tự số", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "bạn chưa nhập số lượng", "lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_vnActionPerformed

    private void vinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vinaActionPerformed
        if (valtdateFrom()) {

            Random rd = new Random();
            String sdt2;
            String[] d = {"088", "091", "094", "081", "082", "083", "084", "085"};

            try {
                int sl = Integer.parseInt(txtVar.getText());
                try {
                    try ( FileWriter fw = new FileWriter("SDTVinaPhone.txt")) {
                        for (int i = 0; i < sl; i++) {
                            int k = rd.nextInt(d.length);
                            int number = 1000000 + rd.nextInt(999999);
                            sdt2 = d[k] + number + ":123456";
                            fw.write(sdt2 + "\n");
                        }
                        fw.close();
                    }
                } catch (IOException ignored) {
                }
                JOptionPane.showMessageDialog(this, "Thành công");

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, e + "\nBạn Phải nhập ký tự số", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "bạn chưa nhập số lượng", "lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_vinaActionPerformed

    private void vtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vtActionPerformed
        if (valtdateFrom()) {

            Random rd = new Random();
            String sdt2;
            String[] d = {"086", "096", "097", "098", "032", "033", "034", "035", "036", "037", "038", "039"};

            try {
                int sl = Integer.parseInt(txtVar.getText());
                try {
                    try ( FileWriter fw = new FileWriter("SDTVietTel.txt")) {
                        for (int i = 0; i < sl; i++) {
                            int k = rd.nextInt(12);
                            int number = 1000000 + rd.nextInt(999999);
                            sdt2 = d[k] + number + ":123456";
                            fw.write(sdt2 + "\n");
                        }
                        fw.close();
                    }
                } catch (IOException ignored) {
                }
                JOptionPane.showMessageDialog(this, "Thành công");

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, e + "\nBạn Phải nhập ký tự số", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "bạn chưa nhập số lượng", "lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_vtActionPerformed

    private void OK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OK2ActionPerformed
        if (valtdateFrom()) {

            Random rd = new Random();
            String sdt2;
            String[] d = {"098", "097", "096", "090", "093", "091", "094", "086"};

            try {
                int sl = Integer.parseInt(txtVar.getText());
                try {
                    try ( FileWriter fw = new FileWriter("CBSDT.txt")) {
                        for (int i = 0; i < sl; i++) {
                            int k = rd.nextInt(8);
                            int number = 1000000 + rd.nextInt(999999);
                            sdt2 = d[k] + number + ":123456";
                            fw.write(sdt2 + "\n");
                        }
                        fw.close();
                    }
                } catch (IOException ignored) {
                }
                JOptionPane.showMessageDialog(this, "Thành công");

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, e + "\nBạn Phải nhập ký tự số", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "bạn chưa nhập số lượng", "lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_OK2ActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        if (valtdateFrom()) {

            Random rd = new Random();
            String sdt;
            String[] d = {"086", "096", "097", "098", "032", "033", "034", "035", "036", "037", "038", "039", "091", "094", "083", "084", "085", "081", "082", "089", "090", "093", "070", "079", "077", "076", "078", "092", "056", "058", "099", "059"};

            try {
                int sl = Integer.parseInt(txtVar.getText());
                try {
                    try ( FileWriter fw = new FileWriter("comboNumber.txt")) {
                        for (int i = 0; i < sl; i++) {
                            int k = rd.nextInt(32);
                            int number = 1000000 + rd.nextInt(999999);
                            sdt = d[k] + number + ":123456";
                            fw.write(sdt + "\n");
                        }
                        fw.close();
                    }
                } catch (IOException ignored) {
                }
                JOptionPane.showMessageDialog(this, "Thành công");

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, e + "\nBạn Phải nhập ký tự số", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "bạn chưa nhập số lượng", "lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnOKActionPerformed
    public boolean valtdateFrom() {
        return !txtVar.getText().isEmpty();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameRandom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameRandom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameRandom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameRandom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFrameRandom().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OK2;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbltime;
    private javax.swing.JButton mobi;
    private javax.swing.JTextField txtVar;
    private javax.swing.JButton vina;
    private javax.swing.JToggleButton vn;
    private javax.swing.JButton vt;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss aa");
        while (true) {
            Date now = new Date();
            String st = sdf.format(now);
            lbltime.setText(st);
            try {
                Thread.sleep(1000);
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi");
            }
        }
    }
}
